# Nathan Benedetto Proença 8941276
# Victor Sena Molero 8941317
GCC_FLAGS=-g -Wall -pedantic -std=c++11
FILES=main

clear:
	rm ${FILES}

ep3: ep3.cpp trace.cpp
	g++ ep3.cpp -pthread ${GCC_FLAGS} -o ep3
