# Nathan Benedetto Proença 8941276
# Victor Sena Molero 8941317
GCC_FLAGS=-g -Wall -pedantic -std=c++11
CPP_FILES=ep3.cpp trace.cpp memory.cpp process.cpp task.cpp page.cpp binaryio.cpp runner.cpp helper.cpp memory_first.cpp

clear:
	rm ${FILES}

ep3: *.cpp *.h
	g++ ${GCC_FLAGS} ${CPP_FILES} -o ep3 -lreadline
